### ISSUE TITLE
array support or resolve references when reference is an array

### ISSUE THREAD

**Issue by eakl** [LeanyLabs/formula-engine#2]
Interesting work. I wonder how the library can implement array support

Let's say I type this:
`2 * ( {{array1}} + {{array2}} )`

with the following mapping
```javascript
const reference = {
  array1: [1, 2, 3, 4, 5],
  array2: [10, 20, 30, 40, 50]
}
```

When resolving the variable as an array, How can the parser / visitor achieve the following:

```
2 * ( 1 + 10 ) = 22
2 * ( 2 + 20 ) = 44
2 * ( 3 + 30 ) = 66
2 * ( 4 + 40 ) = 88
2 * ( 5 + 50 ) = 110
```

End result of the parsing of `2 * ( {{array1}} + {{array2}} )`
should be `[22, 44, 66, 88, 110]`

**Comment by mzahor** [comment]
Hi @eakl . Sorry, somehow I missed the notification about this issue. 
Currently, the engine is relying on JS types and coercion. Which means `[1,1] + [2,2] === '1,12,2'`. But arrays are not supported by lexer, so it won't work out of the box.
In order to achieve meaningful support for arrays, like you've described, you'd need to introduce an "array" data type which would require changes in a few places:
1. tokenizer, to recognize such literals
2. parser, to support array expressions
3. visitor, in order to implement addition/multiplication

Please also note, that this is not as easy as it may seem. Array is a compound data type, and may consists of different primitive and compound data types, which is not straightforward to work with, for example expressions like this: ```['one', 2, [3]] * 2 + ['one', 2, [3]] - ['one', 2, [3]] / 3``` require some predefined rules to be calculated in a meaningful way, that user should be aware of and mini-language should implement.
You can limit the amount of supported scenarios, but again, it'd require some rules.

As an alternative solution, you can define a set of functions to work with arrays, smth like this: 
```
arr(elem1, elem2, elem3);
add_arr(arr1, arr2);
mult_arr(arr, scalar);
// etc...
```
